#include <iostream>
#include <cstdlib>
#include <ctime>
void passwordGenerator(int len);
int main() {
    int l;
    std::cout << "Enter the length of the password:\n";
    std::cin >> l;
    if (l <= 0) {
        std::cout << "Minimum length of the password must be at least 1";
    } else {
        passwordGenerator(l);
    }
    return 0;
}
void passwordGenerator(int len) {
    int r = 0, arrSize = 0, k = 0;
    char pass[len + 1];

    if (len % 4 != 0) {
        arrSize = 4 * (len / 4 + 1);
    } else {
        arrSize = len;
    }

    int ran[arrSize];
    int arr[24][4] = {{1, 2, 3, 4}, {1, 2, 4, 3}, {1, 3, 2, 4}, {1, 3, 4, 2}, {1, 4, 3, 2}, {1, 4, 2, 3}, {2, 1, 3, 4}, {2, 1, 4, 3}, {2, 3, 1, 4}, {2, 3, 4, 1}, {2, 4, 3, 1}, {2, 4, 1, 3}, {3, 2, 1, 4}, {3, 2, 4, 1}, {3, 1, 2, 4}, {3, 1, 4, 2}, {3, 4, 1, 2}, {3, 4, 2, 1}, {4, 2, 3, 1}, {4, 2, 1, 3}, {4, 3, 2, 1},{4, 3, 1, 2}, {4, 1, 3, 2}, {4, 1, 2, 3}};

    std::srand(std::time(nullptr));
    for (int i = 0; i < len; i += 4) {
        r = std::rand() % 24;
        k = 0;
        ran[i] = arr[r][k++];
        ran[i + 1] = arr[r][k++];
        ran[i + 2] = arr[r][k++];
        ran[i + 3] = arr[r][k];
    }

    const char Calpha[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    const char Salpha[] = "abcdefghijklmnopqrstuvwxyz";
    const char n[] = "1234567890";
    const char ch[] = "!@#$%^&*";

    for (int i = 0; i < len; i++) {
        r = ran[i];
        if (r == 1) {
            pass[i] = Calpha[std::rand() % 26];
        } else if (r == 2) {
            pass[i] = Salpha[std::rand() % 26];
        } else if (r == 3) {
            pass[i] = n[std::rand() % 10];
        } else {
            pass[i] = ch[std::rand() % 8];
        }
    }
    pass[len+1] = '\0';
    std::cout << "Password generated by System: " << pass << std::endl;
}
